on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing get hub'
        run: pwd
      - name: 'testing print'
        run: echo basma
  